### PR TITLE
DOC: document move of scripts over to scripts

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by jakirkham** [comment]
Might want to add this in the bot's description as it still links to this repo for reporting issues.

**Comment by CJ-Wright** [comment]
I think the newer PRs link to the scripts https://github.com/regro/cf-scripts/blob/master/03-auto_tick.xsh#L213

**Comment by CJ-Wright** [comment]
Also I put a thing in the issue template saying to move over to the scripts

**Comment by jakirkham** [comment]
To be clear, this is what I'm referring to. If this is as intended, please feel free to ignore. Figured it might not be, hence the note.

screen shot 2018-03-06 at 20 20 07

**Comment by CJ-Wright** [comment]
Thank you! That is not intended (this is why you should never change repos, the names/configurations are left everywhere like fingerprints at a heist)

**Comment by CJ-Wright** [comment]
Now that should be fixed

**Comment by jakirkham** [comment]
Thanks. Looks good.

No kidding. Moving repos (or orgs) is a real pain.

**Pull request merged**
